language: go

go:
  - 1.16.x

os:
    - linux
dist: trusty
sudo: false
branches:
  only:
    - main
install:
  - go get github.com/mattn/goveralls
script:
    - env GO111MODULE=on go build
    # - env GO111MODULE=on go test
    # - $HOME/gopath/bin/goveralls -service=travis-ci
